version: '3'

services:
  redis:
    image: redis
    restart: always
    volumes:
      - redis:/data
  hubot:
    image: timgthomas/snailbot
    build: .
    restart: always
    volumes:
      - ./:/usr/src/app
    depends_on:
      - redis
    ports:
      - 8001:80
    environment:
      - HUBOT_DISCORD_TOKEN
      - REDIS_URL=redis://redis

volumes:
  redis:
